collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_stability"
    cmd_vel_out_topic: "/cmd_vel"
    transform_tolerance: 0.45
    source_timeout: 0.75
    base_shift_correction: True
    stop_pub_timeout: 0.25
    polygons: ["VisualStopZone", "VisualSlowZone"]
    VisualStopZone:
      type: "polygon"
      points: [1.05, 0.58, 1.05, -0.58, -0.45, -0.58, -0.45, 0.58]
      action_type: "stop"
      max_points: 3
      visualize: True
      polygon_pub_topic: "visual_stop_zone"
      enabled: True
    VisualSlowZone:
      type: "polygon"
      points: [1.45, 0.72, 1.45, -0.72, -0.65, -0.72, -0.65, 0.72]
      action_type: "slowdown"
      slowdown_ratio: 0.60
      max_points: 2
      visualize: True
      polygon_pub_topic: "visual_slow_zone"
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan_visual"
      enabled: True
