controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    traction_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    rear_steering_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

traction_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_spin_joint
      - rear_right_wheel_spin_joint
    interface_name: velocity

rear_steering_position_controller:
  ros__parameters:
    joints:
      - rear_left_steering_joint
      - rear_right_steering_joint
    interface_name: position

gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      velocity:
        rear_left_wheel_spin_joint:
          kp: 18.0
          ki: 0.08
          kd: 1.2
          max_integral_error: 1000.0
        rear_right_wheel_spin_joint:
          kp: 18.0
          ki: 0.08
          kd: 1.2
          max_integral_error: 1000.0
      position:
        rear_left_steering_joint:
          kp: 220.0
          ki: 0.0
          kd: 18.0
          max_integral_error: 1000.0
        rear_right_steering_joint:
          kp: 220.0
          ki: 0.0
          kd: 18.0
          max_integral_error: 1000.0
