"""Shared algorithm core for ROS, Gazebo integration, and standalone tests."""

from warehouse_visual_localization.core.command_shaper import CommandShaper, CommandShaperConfig
from warehouse_visual_localization.core.controller import LQRLiteConfig, LQRLiteController, MPPIConfig, MPPIController, PurePursuitConfig, PurePursuitController, SBMPCJAXConfig, SBMPCJAXController, StanleyConfig, StanleyController
from warehouse_visual_localization.core.friction import FrictionConfig, SlipState, estimate_slip
from warehouse_visual_localization.core.localization import EKF2D, EKF2DConfig
from warehouse_visual_localization.core.profiles import VelocityProfileConfig, trapezoid_profile
from warehouse_visual_localization.core.safety import CBFSafetyConfig, CBFSafetyLayer
from warehouse_visual_localization.core.types import ControlCommand, Pose2D, VehicleForces, VehicleParams, VehicleState
from warehouse_visual_localization.core.vehicle_model import FourWheelForkliftModel
from warehouse_visual_localization.core.wheel_kinematics import FourWheelKinematics, WheelCommand, WheelKinematicsResult
from warehouse_visual_localization.core.canonical_constraints import CanonicalConstraintConfig, CanonicalConstraintEvaluator, CanonicalConstraintReport
from warehouse_visual_localization.core.cbf_filter import CBFProjectionResult, filter_linear_cbf_command
from warehouse_visual_localization.core.corridor_geometry import CorridorBoundary, CorridorResult, evaluate_corridor, transform_footprint
from warehouse_visual_localization.core.curvature_speed import CurvatureSpeedConfig, CurvatureSpeedResult, acceleration_limited_speed_profile, curvature_speed_limit, path_to_xy, signed_curvature
from warehouse_visual_localization.core.docking_geometry import DockingConfig, DockingResult, evaluate_docking
from warehouse_visual_localization.core.human_ssm import HumanSSMConfig, HumanSSMResult, evaluate_human_ssm
from warehouse_visual_localization.core.rollover_safety import RolloverConfig, RolloverResult, combined_center_of_gravity, evaluate_rollover, point_in_convex_polygon
from warehouse_visual_localization.core.visual_servo import IBVSResult, PBVSResult, ibvs_command, planar_pbvs_command
